// export const metadata = {
//   title: "My Dashboard",
//   description: "Generated by create next app",
// };

import QuickMenu from "./quickMenu";

export default async function RootLayout({ children }) {
  return (
    <div className="neon-bg-radial-top-right text-secondary-foreground min-h-[72vh]">
      {/* Add background color here */}
      <section className="p-0">
        <div className="container pt-4 pb-4">
          <h1 className="text-primary font-bold">Mina sidor</h1>
        </div>
        <div className="border-primary/25 mb-4 w-full border-b" />
        <div className="container py-4">
          <QuickMenu />
        </div>
        <div className="border-primary/25 my-4 w-full border-b" />
      </section>
      {children}
    </div>
  );
}
